#pragma config(Motor,  port2,           mot2,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           mot3L,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           mot4L,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           mot6R,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           mot7R,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void autonGo()
{
//motor[mot2]=127;
//motor[mot3L]=-127;
//motor[mot4L]=-127;
motor[mot6R]=127;
motor[mot7R]=127;
//wait1Msec(500);
//motor[mot3L]=0;
//motor[mot4L]=0;
//motor[mot6R]=0;
//motor[mot7R]=0;
//wait1Msec(500);
//motor[mot2]=127;
//motor[mot3L]=-127;
//motor[mot4L]=-127;
//motor[mot6R]=127;
//motor[mot7R]=127;
//wait1Msec(500);
////rotate 30 degrees
////motor[mot6R]=127;
////motor[mot7R]=127;
////motor[mot3L]=-127;
////motor[mot4L]=-127;
////wait1Msec(1000);
////motor[mot3L]=0;
////motor[mot4L]=0;
////motor[mot6R]=0;
////motor[mot7R]=0;
////wait1Msec(2000);
//////Move foward for 2nd ball
////motor[mot2]=127;
////motor[mot3L]=127;
////motor[mot4L]=127;
////motor[mot6R]=127;
////motor[mot7R]=127;
////wait1Msec(2000);
//////rotate 30 degrees
////motor[mot6R]=127;
////motor[mot7R]=127;
////motor[mot3L]=-127;
////motor[mot4L]=-127;
////wait1Msec(1000);
////motor[mot3L]=0;
////motor[mot4L]=0;
////motor[mot6R]=0;
////motor[mot7R]=0;
////wait1Msec(1000);
//////Move towards 1st flag
////motor[mot2]=127;
////motor[mot3L]=127;
////motor[mot4L]=127;
////motor[mot6R]=127;
////motor[mot7R]=127;
////wait1Msec(3000);
////motor[mot3L]=0;
////motor[mot4L]=0;
////motor[mot6R]=0;
////motor[mot7R]=0;
//////rotate 30 degrees
////motor[mot6R]=-127;
////motor[mot7R]=-127;
////motor[mot3L]=127;
////motor[mot4L]=127;
////wait1Msec(1000);
////motor[mot3L]=0;
////motor[mot4L]=0;
////motor[mot6R]=0;
////motor[mot7R]=0;
//////Move backwards
////motor[mot6R]=-127;
////motor[mot7R]=-127;
////motor[mot3L]=-127;
////motor[mot4L]=-127;
////wait1Msec(4000);
////motor[mot3L]=0;
////motor[mot4L]=0;
////motor[mot6R]=0;
////motor[mot7R]=0;
//////Rotate right
////motor[mot6R]=-127;
////motor[mot7R]=-127;
////motor[mot3L]=127;
////motor[mot4L]=127;
////wait1Msec(1000);
////motor[mot3L]=0;
////motor[mot4L]=0;
////motor[mot6R]=0;
////motor[mot7R]=0;
//////move forward to 3rd ball
////motor[mot2]=127;
////motor[mot3L]=127;
////motor[mot4L]=127;
////motor[mot6R]=127;
////motor[mot7R]=127;
////wait1Msec(3000);
////motor[mot3L]=0;
////motor[mot4L]=0;
////motor[mot6R]=0;
////motor[mot7R]=0;
////wait1Msec(2000);
//////Rotate left
////motor[mot6R]=-127;
////motor[mot7R]=-127;
////motor[mot3L]=127;
////motor[mot4L]=127;
////wait1Msec(1000);
////motor[mot3L]=0;
////motor[mot4L]=0;
////motor[mot6R]=0;
////motor[mot7R]=0;
////wait1Msec(2000);
////Move towards 4th ball
}
task main()
{
	autonGo();
}
