#pragma config(Sensor, in1,    Pot1,           sensorPotentiometer)
#pragma config(Sensor, in6,    Gyro6,          sensorGyro)
#pragma config(Sensor, dgtl2,  But2,           sensorTouch)
#pragma config(Motor,  port2,           Intake2,       tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void movechassis()
{
	if(SensorValue[But2]==1)
		motor[Intake2]= 127;
	else
		motor[Intake2]= 0;
}
void movechassis2()
{
	if(SensorValue[Pot1]>=3500)
		motor[Intake2]= 127;
	else if (SensorValue[Pot1]<3500 && SensorValue[Pot1]>=1500)
		motor[Intake2]= -127;
	else
		motor[Intake2]= 0;
}
task main()
{
while(true)
{
	movechassis();
	movechassis2();
int x = SensorValue[Pot1];
SensorValue[Pot1]=0;
int y = SensorValue[Gyro6];
SensorValue[Gyro]=0;
}
}
